### ISSUE TITLE
Important question. What kind of spectator list ?

### ISSUE THREAD

**Issue by Crazy0000001** [Misfiy/SpectatorList-SL#1]
I would like to ask you , what does the plugin specifically shows ? Is it the list of spectators , or the list of players spectating you (I'm asking this specific question because some people think that it's the list of players spectating you , but obviously it is not , and only is the list of players that are spectators.) I had an argument with them for now 3days , and they really don't want to listen, until you the maker gives specifications on that. Please and thanks for an answer.

**Comment by obvEve** [comment]
Sorry for late reply but the plugin is intended to show everything currently spectating the player that sees it. It isn't meant to show anyone that isn't spectating you.

**Comment by Crazy0000001** [comment]
alright thanks
